# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oneplus/dumpling/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/oneplus/dumpling/proprietary/vendor/firmware/tp/fw_synaptics_17801.img:system/vendor/firmware/tp/fw_synaptics_17801.img \
    vendor/oneplus/dumpling/proprietary/vendor/lib/hw/fingerprint.goodix.so:system/vendor/lib/hw/fingerprint.goodix.so \
    vendor/oneplus/dumpling/proprietary/vendor/lib/hw/fingerprint.fpc.so:system/vendor/lib/hw/fingerprint.fpc.so \
    vendor/oneplus/dumpling/proprietary/vendor/lib/libgf_ca.so:system/vendor/lib/libgf_ca.so \
    vendor/oneplus/dumpling/proprietary/vendor/lib/libgf_hal.so:system/vendor/lib/libgf_hal.so \
    vendor/oneplus/dumpling/proprietary/vendor/lib/libgoodixfingerprintd_binder.so:system/vendor/lib/libgoodixfingerprintd_binder.so \
    vendor/oneplus/dumpling/proprietary/vendor/lib64/hw/fingerprint.goodix.so:system/vendor/lib64/hw/fingerprint.goodix.so \
    vendor/oneplus/dumpling/proprietary/vendor/lib64/hw/fingerprint.fpc.so:system/vendor/lib64/hw/fingerprint.fpc.so \
    vendor/oneplus/dumpling/proprietary/vendor/lib64/libgf_ca.so:system/vendor/lib64/libgf_ca.so \
    vendor/oneplus/dumpling/proprietary/vendor/lib64/libgf_hal.so:system/vendor/lib64/libgf_hal.so \
    vendor/oneplus/dumpling/proprietary/vendor/lib64/libgoodixfingerprintd_binder.so:system/vendor/lib64/libgoodixfingerprintd_binder.so \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/EU/EU_Bluetooth_cal.acdb:system/vendor/etc/acdbdata/EU/EU_Bluetooth_cal.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/EU/EU_General_cal.acdb:system/vendor/etc/acdbdata/EU/EU_General_cal.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/EU/EU_Global_cal.acdb:system/vendor/etc/acdbdata/EU/EU_Global_cal.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/EU/EU_Handset_cal.acdb:system/vendor/etc/acdbdata/EU/EU_Handset_cal.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/EU/EU_Hdmi_cal.acdb:system/vendor/etc/acdbdata/EU/EU_Hdmi_cal.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/EU/EU_Headset_cal.acdb:system/vendor/etc/acdbdata/EU/EU_Headset_cal.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/EU/EU_Speaker_cal.acdb:system/vendor/etc/acdbdata/EU/EU_Speaker_cal.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/EU/EU_workspaceFile.qwsp:system/vendor/etc/acdbdata/EU/EU_workspaceFile.qwsp \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/MTP/MTP_workspaceFile.qwsp:system/vendor/etc/acdbdata/MTP/MTP_workspaceFile.qwsp \
    vendor/oneplus/dumpling/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:system/vendor/etc/acdbdata/adsp_avs_config.acdb \
    vendor/oneplus/dumpling/proprietary/vendor/etc/qdcm_calib_data_samsung_s6e3fc1_cmd_mode_dsi_panel.xml:system/vendor/etc/qdcm_calib_data_samsung_s6e3fc1_cmd_mode_dsi_panel.xml
