# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm8150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter guacamole guacamoleb guacamoleg hotdog hotdogb,$(TARGET_DEVICE)),)

endif
