# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/instantnoodle/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),instantnoodle)

endif
