# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/instantnoodle/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/instantnoodle

PRODUCT_COPY_FILES += \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/acdbdata/Audio_Parameter_Version.txt:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Audio_Parameter_Version.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/General_cal.acdb \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Global_cal.acdb \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Handset_cal.acdb \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Headset_cal.acdb \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Speaker_cal.acdb \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/camera/ashdr/ncf_pack.ncf:$(TARGET_COPY_OUT_ODM)/etc/camera/ashdr/ncf_pack.ncf \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/camera/ashdr/ncf_pack_imx471.ncf:$(TARGET_COPY_OUT_ODM)/etc/camera/ashdr/ncf_pack_imx471.ncf \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/camera/ashdr/ncf_pack_imx481.ncf:$(TARGET_COPY_OUT_ODM)/etc/camera/ashdr/ncf_pack_imx481.ncf \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/camera/ashdr/ncf_pack_imx586.ncf:$(TARGET_COPY_OUT_ODM)/etc/camera/ashdr/ncf_pack_imx586.ncf \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/camera/calibrationOutput_uw.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/calibrationOutput_uw.bin \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/camera/darksight/darksight_main.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/darksight/darksight_main.bin \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/camera/darksight/darksight_ultrawide.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/darksight/darksight_ultrawide.bin \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/camera/distortion_result.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/distortion_result.bin \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm1.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm1.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm10.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm10.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm11.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm11.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm12.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm12.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm13.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm13.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm14.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm14.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm15.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm15.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm16.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm16.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm17.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm17.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm18.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm18.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm2.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm2.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm3.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm3.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm4.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm4.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm5.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm5.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm6.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm6.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm7.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm7.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm8.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm8.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/inParm9.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/inParm9.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/inparm/irissoft/mcfCheck.txt:$(TARGET_COPY_OUT_ODM)/etc/inparm/irissoft/mcfCheck.txt \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/irissoft.fw:$(TARGET_COPY_OUT_ODM)/etc/irissoft.fw \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/sensor/config/kona_ak991x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_ak991x_0.json \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/sensor/config/kona_bmi26x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_bmi26x_0.json \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/sensor/config/kona_mmc5603x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_mmc5603x_0.json \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/sensor/config/kona_qrd_alsps.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_alsps.json \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/sensor/config/kona_qrd_bmi26x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_bmi26x_0.json \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/sensor/config/kona_qrd_cct.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_cct.json \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/sensor/config/kona_qrd_cct_rear.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_cct_rear.json \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/sensor/config/kona_qrd_icm4x6xx.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_icm4x6xx.json \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/sensor/config/kona_qrd_lsm6dso.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_lsm6dso.json \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/sensor/config/kona_qrd_sx933x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_qrd_sx933x_0.json \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/sensor/config/kona_stk2232_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_stk2232_0.json \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/sensor/config/kona_sx9324_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_sx9324_0.json \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/sensor/config/kona_sx9324up_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/kona_sx9324up_0.json \
    vendor/oneplus/instantnoodle/proprietary/odm/etc/wifi/bdwlan.elf:$(TARGET_COPY_OUT_ODM)/etc/wifi/bdwlan.elf \
    vendor/oneplus/instantnoodle/proprietary/odm/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_ODM)/firmware/tfa98xx.cnt \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/com.qti.sensormodule.ofilm_imx481.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.ofilm_imx481.bin \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/com.qti.sensormodule.ofilm_imx481_SFK.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.ofilm_imx481_SFK.bin \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/com.qti.sensormodule.semco_imx586.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.semco_imx586.bin \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/com.qti.sensormodule.shine_gc2375.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.shine_gc2375.bin \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/com.qti.sensormodule.truly_imx471.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.sensormodule.truly_imx471.bin \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/com.qti.tuned.ofilm_imx481.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.ofilm_imx481.bin \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/com.qti.tuned.semco_imx586.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.semco_imx586.bin \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/com.qti.tuned.shine_gc2375.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.shine_gc2375.bin \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/com.qti.tuned.truly_imx471.bin:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti.tuned.truly_imx471.bin \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/com.qti_instantnoodle.sensor.gc2375.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti_instantnoodle.sensor.gc2375.so \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/com.qti_instantnoodle.sensor.imx471.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti_instantnoodle.sensor.imx471.so \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/com.qti_instantnoodle.sensor.imx481.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti_instantnoodle.sensor.imx481.so \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/com.qti_instantnoodle.sensor.imx586.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/com.qti_instantnoodle.sensor.imx586.so \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/components/com.qti.stats.pdlib.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/components/com.qti.stats.pdlib.so \
    vendor/oneplus/instantnoodle/proprietary/odm/lib64/camera/components/libipebpsstriping.so:$(TARGET_COPY_OUT_ODM)/lib64/camera/components/libipebpsstriping.so \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9608.b00:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b00 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9608.b01:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b01 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9608.b02:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b02 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9608.b03:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b03 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9608.b04:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b04 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9608.b05:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b05 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9608.b06:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b06 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9608.b07:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.b07 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9608.mdt:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9608.mdt \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9638.b00:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b00 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9638.b01:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b01 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9638.b02:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b02 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9638.b03:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b03 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9638.b04:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b04 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9638.b05:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b05 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9638.b06:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b06 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9638.b07:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.b07 \
    vendor/oneplus/instantnoodle/proprietary/odm/vendor/firmware/gfp9638.mdt:$(TARGET_COPY_OUT_ODM)/vendor/firmware/gfp9638.mdt \
    vendor/oneplus/instantnoodle/proprietary/vendor/bin/hw/android.hardware.keymaster@4.0-service-qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.keymaster@4.0-service-qti \
    vendor/oneplus/instantnoodle/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service-qti.rc \
    vendor/oneplus/instantnoodle/proprietary/vendor/lib64/libkeymasterdeviceutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymasterdeviceutils.so \
    vendor/oneplus/instantnoodle/proprietary/vendor/lib64/libkeymasterprovision.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymasterprovision.so \
    vendor/oneplus/instantnoodle/proprietary/vendor/lib64/libkeymasterutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymasterutils.so \
    vendor/oneplus/instantnoodle/proprietary/vendor/lib64/libqtikeymaster4.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqtikeymaster4.so
