# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sdm845-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter enchilada fajita,$(TARGET_DEVICE)),)

endif
